#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     back_left,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool DriveThreshCheck( int parl,int thresh)

{
	return (abs(parl)>thresh);

}

void fatman()
{
	int ljoy = joystick.joy1_y1;
	int rjoy = joystick.joy1_y2;
	if (!DriveThreshCheck(ljoy,20))
	{
		ljoy = 0;


	}
	if (!DriveThreshCheck(rjoy,20))
	{
		rjoy = 0;
	}

	motor[front_left]= -ljoy;
	motor[back_left]= -ljoy;
	motor[front_right]= rjoy;
	motor[back_right]= rjoy;
}
